// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace appWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm formulario;
		
		protected System.Web.UI.WebControls.TextBox txtprimerNombre;
		
		protected System.Web.UI.WebControls.TextBox txtsegundoNombre;
		
		protected System.Web.UI.WebControls.TextBox txtprimerApellido;
		
		protected System.Web.UI.WebControls.TextBox txtsegundoApellido;
		
		protected System.Web.UI.WebControls.TextBox txtNombreCompleto;
		
		protected System.Web.UI.WebControls.CheckBox activo;
		
		protected System.Web.UI.WebControls.TextBox txtCiudad;
		
		protected System.Web.UI.WebControls.TextBox txtDireccion;
		
		protected System.Web.UI.WebControls.TextBox txtTelefono;
		
		protected System.Web.UI.WebControls.TextBox txtIngresos;
	}
}
